/*
 *     Generated by class-dump 3.1.1.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2006 by Steve Nygard.
 */

@interface BRAppliance : NSObject
{
    NSBundle *_myBundle;
}

- (id)applianceControllerWithScene:(id)fp8;
- (float)applianceIconHorizontalOffset;
- (float)applianceIconKerningFactor;
- (float)applianceIconReflectionOffset;
- (id)applianceKey;
- (id)applianceName;
- (void)dealloc;
- (id)init;
- (id)version;

@end

