/*
 *     Generated by class-dump 3.1.1.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2006 by Steve Nygard.
 */

@interface BRControllerStack : NSObject
{
    NSMutableArray *_stack;
    unsigned int _animationsDisabled:1;
    unsigned int _dumpStack:1;
}

- (BOOL)brEventAction:(id)fp8;
- (id)controllerLabelled:(id)fp8;
- (int)count;
- (void)dealloc;
- (id)init;
- (id)peekController;
- (void)popController;
- (void)popToController:(id)fp8;
- (void)popToControllerOfClass:(Class)fp8;
- (void)popToControllerWithLabel:(id)fp8;
- (void)pushController:(id)fp8;
- (void)replaceControllersAboveLabel:(id)fp8 withController:(id)fp12;
- (void)resizeControllers;
- (void)swapController:(id)fp8;

@end

