/*
 *     Generated by class-dump 3.1.1.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2006 by Steve Nygard.
 */

@interface BREvent : NSObject
{
    unsigned short _page;
    unsigned short _usage;
    int _value;
    BOOL _retrigger;
    double _timeStamp;
}

- (id)description;
- (id)initWithPage:(unsigned short)fp8 usage:(unsigned short)fp12 value:(int)fp16;
- (id)initWithPage:(unsigned short)fp8 usage:(unsigned short)fp12 value:(int)fp16 atTime:(double)fp20;
- (BOOL)isEqual:(id)fp8;
- (void)makeRetriggerEvent;
- (unsigned short)page;
- (unsigned int)pageUsageHash;
- (BOOL)retriggerEvent;
- (double)timeStamp;
- (unsigned short)usage;
- (int)value;

@end

