/*
 *     Generated by class-dump 3.1.1.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2006 by Steve Nygard.
 */

#import <BRMetadataLinesLayer.h>

@interface BRMetadataLinesLayer (Private)
- (void)_buildLineLayersForValues:(id)fp8 andLabels:(id)fp12 usingIndexes:(id)fp16;
- (void)_layoutLines;
- (void)_setLineHeightUsingValues:(id)fp8 andLabels:(id)fp12;
- (id)_visibleMetadataIndexesForHeight:(float)fp8 andValues:(id)fp12;
- (float)_widthOfWidestLabel;
@end

