/*
 *     Generated by class-dump 3.1.1.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2006 by Steve Nygard.
 */

#import <BRRenderLayer.h>
#import <BRDividerLayer.h>
#import <BRImageLayer.h>
#import <BRMetadataLinesLayer.h>
#import <BRTextLayer.h>

@interface BRMetadataLayer : BRRenderLayer
{
    BRTextLayer *_titleLayer;
    BRImageLayer *_ratingImageLayer;
    BRTextLayer *_summaryLayer;
    BRMetadataLinesLayer *_metadataLinesLayer;
    BRTextLayer *_copyrightLayer;
    BRDividerLayer *_topDividerLayer;
    BRDividerLayer *_middleDividerLayer;
    BRDividerLayer *_bottomDividerLayer;
    NSArray *_metadataObjs;
    NSArray *_metadataLabels;
    float _frameWidth;
    float _maxHeight;
    float _titleLineHeight;
    float _summaryLineHeight;
    float _topDividerHeight;
    float _middleDividerHeight;
    float _bottomDividerHeight;
}

- (void)dealloc;
- (id)initWithScene:(id)fp8;
- (void)resetAllFields;
- (void)setCopyright:(id)fp8;
- (void)setFrame:(struct _NSRect)fp8;
- (void)setMaxHeight:(float)fp8;
- (void)setMetadata:(id)fp8 withLabels:(id)fp12;
- (void)setOrigin:(struct _NSPoint)fp8;
- (void)setRating:(id)fp8;
- (void)setSummary:(id)fp8;
- (void)setTitle:(id)fp8;
- (void)setWidth:(float)fp8;

@end

