/*
 *     Generated by class-dump 3.1.1.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2006 by Steve Nygard.
 */

#import <BRQTKitVideoPlayer.h>

@interface BRQTKitVideoPlayer (RateTimer)
- (void)_cancelRateTimer;
- (void)_decrementRateTimerFired:(id)fp8;
- (void)_incrementRateTimerFired:(id)fp8;
- (void)_startDecrementRateTimer;
- (void)_startIncrementRateTimer;
@end

