/*
 *     Generated by class-dump 3.1.1.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2006 by Steve Nygard.
 */

#import <BRVideoPlayer.h>

@class BRVideo, BRVideoPlayerStateMachine, NSTimer;

@interface BRQTKitVideoPlayer : BRVideoPlayer
{
    BRVideo *_video;
    float _aspectRatio;
    NSTimer *_rateTimer;
    double _virtualChapterMark;
    double _virtualChapterMarkExpiration;
    BRVideoPlayerStateMachine *_stateMachine;
    unsigned int _showFrames:1;
    unsigned int _gatherStats:1;
    unsigned int _muted:1;
}

- (float)aspectRatio;
- (struct BRVideoTimeRange)bufferedRange;
- (float)bufferingProgress;
- (id)currentChapterTitle;
- (struct __CVBuffer *)currentFrame;
- (void)dealloc;
- (float)elapsedPlaybackTime;
- (id)init;
- (BOOL)initiatePlayback:(id *)fp8;
- (void)leftArrowClick;
- (BOOL)muted;
- (BOOL)newFrameForTime:(const CDAnonymousStruct1 *)fp8 frame:(struct __CVBuffer **)fp12;
- (void)pause;
- (void)play;
- (int)playerState;
- (BOOL)prerollMedia:(id *)fp8;
- (void)pressAndHoldLeftArrow;
- (void)pressAndHoldRightArrow;
- (void)resume;
- (void)rightArrowClick;
- (void)setCaptionsEnabled:(BOOL)fp8;
- (void)setContextSizeHint:(struct _NSSize)fp8;
- (void)setElapsedPlaybackTime:(float)fp8;
- (BOOL)setMedia:(id)fp8 error:(id *)fp12;
- (void)setMovieLoops:(BOOL)fp8;
- (void)setMuted:(BOOL)fp8;
- (void)setPlaybackContext:(id)fp8;
- (void)stop;
- (double)trackDuration;

@end

