/*
 *     Generated by class-dump 3.1.1.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2006 by Steve Nygard.
 */

#import <BRQTKitVideoPlayer.h>

@interface BRQTKitVideoPlayer (PlaybackControl)
- (void)_handleSideEffect:(int)fp8;
- (void)_postAction:(int)fp8 playSound:(BOOL)fp12;
- (void)_updateAspectRatio;
- (void)_updatePlayerForState:(id)fp8;
@end

