/*
 *     Generated by class-dump 3.1.1.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2006 by Steve Nygard.
 */

#import <BRQTKitVideoPlayer.h>

@interface BRQTKitVideoPlayer (MovieNotifications)
- (void)_videoAspectRatioNotification:(id)fp8;
- (void)_videoBufferingChangedNotification:(id)fp8;
- (void)_videoLoadErrorNotification:(id)fp8;
- (void)_videoPlayableHandler:(id)fp8;
- (void)_videoPlaybackHitBeginningHandler:(id)fp8;
- (void)_videoPlaybackHitEndHandler:(id)fp8;
- (void)_videoRateDroppedHandler:(id)fp8;
- (void)_videoTimeChangedNotification:(id)fp8;
@end

