/*
 *     Generated by class-dump 3.1.1.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2006 by Steve Nygard.
 */

#import <BRRenderDisplayLink.h>

@interface BRRenderDisplayLink (DisplayTracking)
- (void)_displayOfflineHandler:(id)fp8;
- (void)_displayOnlineHandler:(id)fp8;
- (void)_startDisplayLink;
- (void)_stopDisplayLink;
@end

