/*
 *     Generated by class-dump 3.1.1.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2006 by Steve Nygard.
 */

#import <BRRenderDisplayLink.h>

@interface BRRenderDisplayLink (DisplayLinkFired)
- (int)_updateFrameForTime:(const CDAnonymousStruct1 *)fp8;
@end

