/*
 *     Generated by class-dump 3.1.1.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2006 by Steve Nygard.
 */

#import <BRRenderLayer.h>
#import <BRTexture.h>
#import <BRWaitSpinnerLayer.h>

@interface BRSelectionLozengeLayer : BRRenderLayer
{
    BRTexture *_leftImage;
    BRTexture *_rightImage;
    BRTexture *_centerImage;
    unsigned int _displayListID;
    BRWaitSpinnerLayer *_spinner;
}

- (void)dealloc;
- (id)initWithScene:(id)fp8;
- (float)overHangForRowHeight:(float)fp8;
- (float)overHeightFactor;
- (void)renderLayer;
- (void)setFrame:(struct _NSRect)fp8;
- (float)underHangForRowHeight:(float)fp8;
- (id)waitSpinner;

@end

