/*
 *     Generated by class-dump 3.1.1.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2006 by Steve Nygard.
 */
#import "BRRenderScene.h"

@interface BRControl : NSObject
{
    BRRenderScene *_scene;
}

+ (id)controlWithScene:(id)fp8;
- (float)alphaValue;
- (BOOL)brEventAction:(id)fp8;
- (void)dealloc;
- (struct _NSRect)frame;
- (BOOL)hidden;
- (id)initWithScene:(id)fp8;
- (id)layer;
- (id)scene;
- (void)setAlphaValue:(float)fp8;
- (void)setFrame:(struct _NSRect)fp8;
- (void)setHidden:(BOOL)fp8;

@end

