/*
 *     Generated by class-dump 3.1.1.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2006 by Steve Nygard.
 */

#import <BRRenderLayer.h>

@interface BRDividerLayer : BRRenderLayer
{
    float _lineStart;
    float _lineEnd;
    float _lineThickness;
    float _verticalPosition;
}

- (id)initWithScene:(id)fp8;
- (void)renderLayer;
- (void)setFrame:(struct _NSRect)fp8;
- (void)setVerticalPosition:(float)fp8;

@end

