/*
 *     Generated by class-dump 3.1.1.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2006 by Steve Nygard.
 */

#import <BRControllerStack.h>
#import <BRRenderLayer.h>
#import <BRRenderScene.h>

@interface BRLayerController : NSObject
{
    NSMutableDictionary *_labels;
    NSArray *_controls;
    BRControllerStack *_stack;
    BRRenderScene *_scene;
    BRRenderLayer *_master;
}

+ (id)layerControllerWithScene:(id)fp8;
- (void)addControl:(id)fp8;
- (void)addLabel:(id)fp8;
- (BOOL)brEventAction:(id)fp8;
- (id)buryAnimationWithPushingController:(id)fp8;
- (id)controls;
- (void)dealloc;
- (id)exhumeAnimationWithPoppingController:(id)fp8;
- (BOOL)firstResponder;
- (id)initWithScene:(id)fp8;
- (BOOL)isLabelled:(id)fp8;
- (BOOL)isNetworkDependent;
- (id)masterLayer;
- (struct _NSRect)masterLayerFrame;
- (id)popAnimation;
- (BOOL)popsOnBury;
- (id)pushAnimation;
- (void)removeLabel:(id)fp8;
- (void)resetLayout;
- (id)scene;
- (void)setControls:(id)fp8;
- (void)setStack:(id)fp8;
- (id)stack;
- (void)wasBuriedByPushingController:(id)fp8;
- (void)wasExhumedByPoppingController:(id)fp8;
- (void)wasPopped;
- (void)wasPushed;
- (void)willBeBuried;
- (void)willBeExhumed;
- (void)willBePopped;
- (void)willBePushed;

@end

