/*
 *     Generated by class-dump 3.1.1.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2006 by Steve Nygard.
 */

#import "BRControl.h"
#import "BRMenuListLayer.h"

@interface BRListControl : BRControl
{
    BRMenuListLayer *_list;
    long _scrollTarget;
    long _scrollStart;
    double _scrollRateMin;
    double _scrollRate;
    double _scrollRamp;
    double _prevTime;
    double _timeFreq;
    double _startTime;
    double _currentRate;
    double _lastActivityUpdate;
    long _direction;
    BOOL _changedDirectionWhileScrolling;
    unsigned int _inScroll:1;
    unsigned int _stopScroll:1;
    unsigned int _keyupReceived:1;
    unsigned int _scrollUnbounded:1;
    unsigned int _slowDown:1;
    unsigned int _active:1;
    unsigned int _smoothScroll:1;
}

- (void)addDividerAtIndex:(long)fp8;
- (BOOL)brEventAction:(id)fp8;
- (id)datasource;
- (void)dealloc;
- (id)initWithScene:(id)fp8;
- (id)layer;
- (struct _NSRect)listTextFrame;
- (long)maximumVisibleItemsForListHeight:(float)fp8;
- (float)minimumRowHeightForVisibleItems:(long)fp8;
- (void)reload;
- (void)removeDividerAtIndex:(long)fp8;
- (double)selection;
- (void)setDatasource:(id)fp8;
- (void)setDividerIndex:(long)fp8;
- (void)setRowHeight:(float)fp8;
- (void)setSelection:(double)fp8;
- (void)stopScrolling;
- (void)willBeDeactivated;
- (void)willBeReactivated;

@end

