/*
 *     Generated by class-dump 3.1.1.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2006 by Steve Nygard.
 */

#import <BRRenderLayer.h>
#import <BRDividerLayer.h>

@interface BRListLayer : BRRenderLayer
{
    NSMutableDictionary *_dividerLayers;
    NSDictionary *_dividers;
    NSArray *_rows;
    BRDividerLayer *_dividerLayer;
    float _rowHeight;
    float _translation;
    float _dividerIndex;
}

- (BOOL)clipsToFrame;
- (void)dealloc;
- (id)initWithScene:(id)fp8;
- (void)removeDividerLayerForKey:(id)fp8;
- (float)rowHeight;
- (id)rows;
- (float)scrollTranslate;
- (void)setDividers:(id)fp8;
- (void)setRowHeight:(float)fp8;
- (void)setRows:(id)fp8;
- (void)setScrollTranslate:(float)fp8;

@end

