/*
 *     Generated by class-dump 3.1.1.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2006 by Steve Nygard.
 */

#import <BRRenderLayer.h>
#import <BRSelectionLozengeLayer.h>
#import <BRListLayer.h>

@interface BRMenuListLayer : BRRenderLayer
{
    id _source;
    NSMutableDictionary *_dividers;
    long _rowCount;
    long _maxVisibleRows;
    struct _NSRange _visibleRange;
    long _selection;
    double _remainder;
    double _widgetOverheightFactor;
    BRListLayer *_list;
    BRSelectionLozengeLayer *_widget;
    unsigned int _neededScrollingPreviously:1;
}

- (void)addDividerAtIndex:(long)fp8;
- (long)currentWidgetIndex;
- (id)datasource;
- (void)dealloc;
- (float)extraWidgetSpace;
- (id)initWithScene:(id)fp8;
- (long)itemCount;
- (long)maxVisibleRows;
- (long)maximumVisibleItemsForListHeight:(float)fp8;
- (float)minimumRowHeightForVisibleItems:(long)fp8;
- (void)reload;
- (void)removeDividerAtIndex:(long)fp8;
- (float)rowHeight;
- (id)selectedRowObject;
- (double)selection;
- (void)setDatasource:(id)fp8;
- (void)setDividerIndex:(long)fp8;
- (void)setFrame:(struct _NSRect)fp8;
- (void)setRowHeight:(float)fp8;
- (void)setSelection:(double)fp8;
- (struct _NSRect)textFrame;
- (id)visibleRows;
- (id)waitSpinner;

@end

