/*
 *     Generated by class-dump 3.1.1.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2006 by Steve Nygard.
 */

#import <BRLayerController.h>
#import <BRImageLayer.h>
#import <BRListControl.h>
#import <BRTextLayer.h>

@interface BRMenuController : BRLayerController
{
    BRListControl *_listControl;
    BRImageLayer *_listIcon;
    float _listIconHorizontalOffset;
    float _listIconKerningFactor;
    unsigned int _keepIconSpace:1;
    NSArray *_menuPath;
    unsigned int _preSelectedIndexCalculated:1;
    NSArray *_dataSet;
    id _selectedObject;
    BRTextLayer *_listTitle;
}

+ (struct _NSRect)listFrameForBounds:(struct _NSSize)fp8;
- (struct _NSRect)applianceIconFrame;
- (void)dealloc;
- (long)defaultIndex;
- (void)frameForTitleIcon:(struct _NSRect *)fp8 andText:(struct _NSRect *)fp12 forBounds:(struct _NSSize)fp16;
- (BOOL)indexForPreviousSelection:(long *)fp8;
- (id)initWithScene:(id)fp8;
- (BOOL)isCurrentSelectionValidForModelData:(id)fp8;
- (BOOL)isVolatile;
- (void)itemSelected:(long)fp8;
- (id)list;
- (struct _NSRect)listFrameForBounds:(struct _NSSize)fp8;
- (id)listIcon;
- (float)listIconHorizontalOffset;
- (float)listIconKerningFactor;
- (float)listIconYFactor;
- (id)listTitle;
- (id)loadModelData;
- (void)refreshControllerForModelUpdate;
- (void)resetLayout;
- (id)selectedObject;
- (void)setApplianceIcon:(id)fp8;
- (void)setApplianceIconHidden:(BOOL)fp8;
- (void)setListIcon:(id)fp8;
- (void)setListIcon:(id)fp8 horizontalOffset:(float)fp12 kerningFactor:(float)fp16;
- (void)setListIconHorizontalOffset:(float)fp8;
- (void)setListIconKerningFactor:(float)fp8;
- (void)setListTitle:(id)fp8;
- (void)setPreSelectedIndex;
- (void)setSelectedObject:(id)fp8;
- (BOOL)shouldRefreshForUpdateToObject:(id)fp8;
- (int)soundForSelectingItem:(long)fp8;
- (void)willBeBuried;
- (void)willBeExhumed;
- (void)willBePopped;
- (void)willBePushed;

@end

