/*
 *     Generated by class-dump 3.1.1.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2006 by Steve Nygard.
 */

#import <Cocoa/Cocoa.h>
//#import <BRRenderScene.h>

@class BRRenderScene;

@interface BRRenderDisplayLink : NSObject
{
    BRRenderScene *_scene;
    NSMutableSet *_items;
    struct __CVDisplayLink *_link;
    long _frameCount;
    double _frameTimeAccum;
    double _prevFrameTime;
    unsigned int _needsDisplay:1;
    unsigned int _stopFakeThread:1;
    unsigned int _beamSyncDisabled:1;
    unsigned int _updateFramerate:1;
    unsigned int _logItems:1;
}

- (void)addItemToLink:(id)fp8;
- (void)dealloc;
- (id)initWithScene:(id)fp8;
- (BOOL)isRunning;
- (void)needsDisplay;
- (void)removeLinkItem:(id)fp8;
- (void)setUpdateFramerate:(BOOL)fp8;

@end

