/*
 *     Generated by class-dump 3.1.1.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2006 by Steve Nygard.
 */

#import <BRRenderLayer.h>

@class BRAutoScrollingTextLayer, BRTextLayer, BRWaitSpinnerControl, NSArray;

@interface BRTextMenuItemLayer : BRRenderLayer
{
    BRTextLayer *_textLine;
    BRAutoScrollingTextLayer *_scrollingLine;
    BRTextLayer *_rightJustifiedTextLayer;
    NSArray *_tabStops;
    struct _NSSize _textBounds;
    struct _NSSize _rightJustifiedTextBounds;
    BOOL _rightTextShouldHighlight;
    BRRenderLayer *_arrow;
    BRWaitSpinnerControl *_spinner;
    unsigned int _disableArrow:1;
    unsigned int _highlighted:1;
    unsigned int _menuTextCentered:1;
    float _textIconWidth;
}

+ (id)folderMenuItemWithScene:(id)fp8;
+ (id)menuItemWithScene:(id)fp8;
+ (id)networkMenuItemWithScene:(id)fp8;
+ (id)progressFolderItemWithScene:(id)fp8;
+ (id)progressMenuItemWithScene:(id)fp8;
- (BOOL)arrowDisabled;
- (void)dealloc;
- (void)highlight;
- (id)icon;
- (struct _NSSize)iconSize;
- (id)initWithScene:(id)fp8;
- (struct _NSSize)renderedSize;
- (id)rightJustifiedText;
- (BOOL)rightTextShouldHighlight;
- (void)scrollItemIfNecessary;
- (void)setAlphaValue:(float)fp8;
- (void)setArrowDisabled:(BOOL)fp8;
- (void)setFrame:(struct _NSRect)fp8;
- (void)setRightJustifiedText:(id)fp8;
- (void)setRightJustifiedText:(id)fp8 attributes:(id)fp12;
- (void)setRightTextShouldHighlight:(BOOL)fp8;
- (void)setTabStops:(id)fp8;
- (void)setTextIconWidth:(float)fp8;
- (void)setTitle:(id)fp8;
- (void)setTitle:(id)fp8 centered:(BOOL)fp12;
- (void)setWaitSpinnerActive:(BOOL)fp8;
- (struct _NSSize)spinnerSize;
- (void)stopScrollingItem;
- (id)title;
- (void)unHighlight;

@end

