/*
 *     Generated by class-dump 3.1.1.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2006 by Steve Nygard.
 */

@interface BRType : NSObject
{
    NSString *_typeString;
}

+ (id)typeEnumerator;
+ (id)typeForString:(id)fp8;
+ (id)unknown;
- (void)dealloc;
- (id)initWithString:(id)fp8;
- (id)typeString;

@end

