/*
 *     Generated by class-dump 3.1.1.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2006 by Steve Nygard.
 */

#import <BRRenderLayer.h>

@interface BRWaitSpinnerLayer : BRRenderLayer
{
    long _progressPhase;
    double _timeFreq;
    double _prevTime;
    NSMutableData *_textureData;
    unsigned int _textureID;
    int _textureSize;
}

- (void)dealloc;
- (id)initWithScene:(id)fp8;
- (void)nextPhase;
- (void)renderLayer;
- (void)reset;
- (void)setFrame:(struct _NSRect)fp8;
- (BOOL)updateFrameForTime:(const CDAnonymousStruct1 *)fp8;

@end

