/*
 *     Generated by class-dump 3.1.1.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2006 by Steve Nygard.
 */

#import <BRRenderScene.h>

@interface BRAnimation : NSObject
{
    BRRenderScene *_scene;
    int _curve;
    double _duration;
    float _position;
    double _timeFreq;
    double _startTime;
    double _minTime;
    double _prevFrameTime;
    unsigned int _sceneWarmed:1;
    unsigned int _animationRunning:1;
    unsigned int _async:1;
    unsigned int _loops:1;
}

+ (id)animationWithScene:(id)fp8;
- (BOOL)animationRunning;
- (BOOL)asynchronous;
- (int)curve;
- (void)dealloc;
- (double)duration;
- (id)initWithScene:(id)fp8;
- (BOOL)loops;
- (float)position;
- (void)positionChanged:(float)fp8;
- (void)run;
- (id)scene;
- (void)setAnimationCurve:(int)fp8;
- (void)setAsynchronous:(BOOL)fp8;
- (void)setDuration:(double)fp8;
- (void)setLoops:(BOOL)fp8;
- (void)setMinimumUpdateTime:(double)fp8;
- (void)setPosition:(float)fp8;
- (void)stop;

@end

