/*
 *     Generated by class-dump 3.1.1.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2006 by Steve Nygard.
 */

#import "BRRenderLayer.h"
#import "BRTexture.h"

@interface BRImageLayer : BRRenderLayer
{
    BRTexture *_texture;
    float _reflectionAmount;
    float _reflectionOffset;
    float _yRotation;
    unsigned int _disableBlend:1;
}

- (void)dealloc;
- (BOOL)disableBlending;
- (struct _NSSize)pixelBounds;
- (float)reflectionAmount;
- (float)reflectionOffset;
- (void)renderLayer;
- (void)setDisableBlending:(BOOL)fp8;
- (void)setImage:(struct CGImage *)fp8;
- (void)setImage:(struct CGImage *)fp8 downsampleTo:(struct _NSSize)fp12;
- (void)setReflectionAmount:(float)fp8;
- (void)setReflectionOffset:(float)fp8;
- (void)setTexture:(id)fp8;
- (void)setYRotation:(float)fp8;
- (id)texture;
- (float)yRotation;

@end

