/*
 *     Generated by class-dump 3.1.1.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2006 by Steve Nygard.
 */

#import <BRLocalizedStringManager.h>

@interface BRLocalizedStringManager (Private)
- (id)_currentLanguageNameForBundle:(id)fp8;
- (void)_languageChanged:(id)fp8;
@end

