/*
 *     Generated by class-dump 3.1.1.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2006 by Steve Nygard.
 */

#import <BRSingleton.h>

@interface BRLocalizedStringManager : BRSingleton
{
    NSString *_currentLanguage;
    NSMutableDictionary *_stringFileCache;
}

+ (id)appliance:(id)fp8 localizedStringForKey:(id)fp12 inFile:(id)fp16;
+ (id)applicationLocalizedStringForKey:(id)fp8 inFile:(id)fp12;
+ (id)backRowLocalizedStringForKey:(id)fp8 inFile:(id)fp12;
+ (id)localizedStringForKey:(id)fp8 inFile:(id)fp12 fromBundle:(id)fp16;
+ (void)setSingleton:(id)fp8;
+ (id)singleton;
- (void)dealloc;
- (id)init;

@end

