/*
 *     Generated by class-dump 3.1.1.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2006 by Steve Nygard.
 */

#import <BRMediaMenuController.h>

@interface BRMediaMenuController (MusicStoreInformalProtocol)
- (void)checkMusicStoreLoadState:(id)fp8;
- (BOOL)menuDisplaysLeftIcon;
- (id)menuItemsForMusicStoreCollections;
- (id)musicStoreBaseType;
- (id)musicStoreCollectionForIndex:(long)fp8;
- (id)musicStoreCollections;
- (id)musicStoreController;
- (id)musicStorePreviewController;
- (void)networkStateChanged:(id)fp8;
@end

