/*
 *     Generated by class-dump 3.1.1.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2006 by Steve Nygard.
 */

#import <BRType.h>

@interface BRMediaType : BRType
{
    BRMediaType *_derivedFrom;
}

+ (id)TVShow;
+ (id)TVShowPreview;
+ (id)audioBook;
+ (id)booklet;
+ (id)coachedAudio;
+ (void)initialize;
+ (id)interactiveBooklet;
+ (id)movie;
+ (id)moviePreview;
+ (id)movieTrailer;
+ (id)musicVideo;
+ (id)musicVideoPreview;
+ (id)photo;
+ (id)podcast;
+ (id)song;
+ (id)songPreview;
- (void)dealloc;
- (id)parentType;
- (void)setParentType:(id)fp8;

@end

