/*
 *     Generated by class-dump 3.1.1.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2006 by Steve Nygard.
 */

#import <BRTexture.h>
#import <CDStructures.h>
#import <BRRenderContext.h>

@interface BRPBufferTexture : BRTexture
{
    struct BRTextureInfo _info;
    BRRenderContext *_context;
    struct _CGLPBufferObject *_buffer;
}

- (void)dealloc;
- (id)initWithSize:(struct _NSSize)fp8 sharedContext:(id)fp16;
- (id)initWithSize:(struct _NSSize)fp8 sharedContext:(id)fp16 pixelFormat:(id)fp20;
- (id)textureContext;
- (const struct BRTextureInfo *)textureInfo;

@end

