/*
 *     Generated by class-dump 3.1.1.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2006 by Steve Nygard.
 */

#import <BRPBufferTexture.h>
#import <BRRenderContext.h>
#import <BRRenderScene.h>

@interface BRRenderLayer : NSObject
{
    BRRenderScene *_scene;
    BRRenderContext *_context;
    BRRenderLayer *_superlayer;
    NSMutableArray *_sublayers;
    id _effectsDelegate;
    BRPBufferTexture *_effectsTexture;
    float _zPosition;
    struct _NSRect _frame;
    float _alpha;
    unsigned int _needsUpdates:1;
    unsigned int _clipsAtFrame:1;
    unsigned int _hidden:1;
    unsigned int _drawFrameOutline:1;
}

+ (id)layerWithScene:(id)fp8;
- (void)addSublayer:(id)fp8;
- (float)alphaValue;
- (BOOL)clipsToFrame;
- (id)context;
- (void)dealloc;
- (id)effectsDelegate;
- (struct _NSRect)frame;
- (BOOL)hidden;
- (id)initWithScene:(id)fp8;
- (void)insertSublayer:(id)fp8 above:(id)fp12;
- (void)insertSublayer:(id)fp8 atIndex:(long)fp12;
- (void)insertSublayer:(id)fp8 below:(id)fp12;
- (BOOL)needsUpdates;
- (void)removeFromSuperlayer;
- (void)renderLayer;
- (void)replaceSublayer:(id)fp8 with:(id)fp12;
- (id)scene;
- (void)setAlphaValue:(float)fp8;
- (void)setEffectsDelegate:(id)fp8;
- (void)setFrame:(struct _NSRect)fp8;
- (void)setHidden:(BOOL)fp8;
- (void)setNeedsUpdates:(BOOL)fp8;
- (void)setSublayers:(id)fp8;
- (void)setZPosition:(float)fp8;
- (id)sublayers;
- (id)superlayer;
- (BOOL)updateFrameForTime:(const CDAnonymousStruct1 *)fp8;
- (float)zPosition;

@end

