/*
 *     Generated by class-dump 3.1.1.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2006 by Steve Nygard.
 */

//#import <BRRenderContext.h>
#import <BRRenderDisplayLink.h>
//#import <BRRenderLayer.h>

@class BRRenderLayer, BRRenderContext;

@interface BRRenderScene : NSObject
{
    BRRenderContext *_context;
    BRRenderContext *_resourceContext;
    BRRenderLayer *_root;
    struct _NSSize _sceneSize;
    unsigned int _setupList;
    BRRenderDisplayLink *_displayLink;
    NSMutableDictionary *_textureCache;
    float _backupDistance;
    float _backClipping;
    float _frontClipping;
    float _aspectRatio;
    float _fov;
    unsigned int _opaque:1;
    unsigned int _dumpTree:1;
    unsigned int _drawFrameRate:1;
    unsigned int _drawSafeRegions:1;
    double _frameRate;
    long _perfFrameCount;
    double _perfMarkTime;
    unsigned int _perfLoggingEnabled:1;
}

- (float)backClipping;
- (id)cachedTextureForKey:(id)fp8;
- (void)dealloc;
- (id)displayLink;
- (float)frontClipping;
- (id)init;
- (struct _NSRect)interfaceFrame;
- (void)perfLogTimeDiffWithMessage:(id)fp8;
- (void)perfMarkTime;
- (id)qcContext;
- (void)renderScene;
- (void)resetCachedTextures;
- (id)resourceContext;
- (id)root;
- (void)setCachedTexture:(id)fp8 forKey:(id)fp12;
- (void)setDrawableContext:(id)fp8;
- (void)setRoot:(id)fp8;
- (void)setSize:(struct _NSSize)fp8;
- (struct _NSSize)size;

@end

