/*
 *     Generated by class-dump 3.1.1.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2006 by Steve Nygard.
 */

#import <BRBaseMediaAsset.h>

@interface BRSimpleMediaAsset : BRBaseMediaAsset
{
    NSURL *_mediaURL;
}

- (void)dealloc;
- (id)initWithMediaURL:(id)fp8;
- (id)mediaURL;

@end

