/*
 *     Generated by class-dump 3.1.1.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2006 by Steve Nygard.
 */

#import <BRRenderLayer.h>

@class BRTexture, NSAttributedString;

@interface BRTextLayer : BRRenderLayer
{
    NSAttributedString *_string;
    struct __CTFramesetter *_framesetter;
    struct __CTTypesetter *_typesetter;
    struct __CTLine *_truncationToken;
    struct _NSSize _maxSize;
    struct _NSSize _textureSize;
    struct _NSSize _textureFramedSize;
    BRTexture *_texture;
    unsigned int _colorText:1;
}

- (id)attributedString;
- (BOOL)colorText;
- (void)dealloc;
- (struct _NSSize)maxSize;
- (void)renderLayer;
- (struct _NSSize)renderedSize;
- (void)setAttributedString:(id)fp8;
- (void)setColorText:(BOOL)fp8;
- (void)setMaxSize:(struct _NSSize)fp8;
- (id)texture;

@end

