/*
 *     Generated by class-dump 3.1.1.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2006 by Steve Nygard.
 */

#import <BRMediaPlayer.h>

@class BRRenderContext;

@interface BRVideoPlayer : BRMediaPlayer
{
    BRRenderContext *_context;
    struct _NSSize _contextSize;
    unsigned int _enableCaptions:1;
    unsigned int _loops:1;
}

- (float)aspectRatio;
- (struct BRVideoTimeRange)bufferedRange;
- (BOOL)captionsEnabled;
- (struct _NSSize)contextSizeHint;
- (struct __CVBuffer *)currentFrame;
- (void)dealloc;
- (id)init;
- (BOOL)movieLoops;
- (BOOL)newFrameForTime:(const CDAnonymousStruct1 *)fp8 frame:(struct __CVBuffer **)fp12;
- (id)playbackContext;
- (BOOL)prerollMedia:(id *)fp8;
- (void)setCaptionsEnabled:(BOOL)fp8;
- (void)setContextSizeHint:(struct _NSSize)fp8;
- (void)setMovieLoops:(BOOL)fp8;
- (void)setPlaybackContext:(id)fp8;

@end

