/*
 *     Generated by class-dump 3.1.1.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2006 by Steve Nygard.
 */

#import <BRMediaPlayerController.h>

@class BRBlackFadeoutLayer, BRImageLayer, BRListControl, BRQuadLayer, BRTransportControl, BRVideoPlayer, BRVideoPlayerHostLayer, NSArray, NSDictionary, NSMutableDictionary, NSTimer;

@interface BRVideoPlayerController : BRMediaPlayerController
{
    BRVideoPlayer *_player;
    BRVideoPlayerHostLayer *_host;
    BRBlackFadeoutLayer *_fade;
    BRQuadLayer *_blurFadeBackground;
    BRImageLayer *_blurredFrame;
    BRListControl *_resumeMenu;
    BRTransportControl *_transport;
    NSArray *_savedLayers;
    NSDictionary *_committedCCLayers;
    NSMutableDictionary *_nextCCLayers;
    NSTimer *_suppressBackgroundProcessTimer;
    unsigned int _allowsResume:1;
    unsigned int _drmSyncAttempted:1;
    unsigned int _transportInhibited:1;
}

- (BOOL)allowsResume;
- (id)buryAnimationWithPushingController:(id)fp8;
- (void)dealloc;
- (id)exhumeAnimationWithPoppingController:(id)fp8;
- (id)player;
- (id)popAnimation;
- (id)pushAnimation;
- (void)resetLayout;
- (void)setAllowsResume:(BOOL)fp8;
- (void)setTransportControlInhibited:(BOOL)fp8;
- (void)setVideoPlayer:(id)fp8;
- (BOOL)transportControlInhibited;
- (id)videoPlayer;
- (void)wasBuriedByPushingController:(id)fp8;
- (void)wasExhumedByPoppingController:(id)fp8;
- (void)wasPopped;
- (void)wasPushed;
- (void)willBeBuried;
- (void)willBeExhumed;
- (void)willBePopped;
- (void)willBePushed;

@end

